kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: vector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vector
    spec:
      serviceAccount: vector
      serviceAccountName: vector
      containers:
        - name: vector
          image: {{ .Values.image }}
          args: ["--config-dir","/etc/vector/"]
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PROCFS_ROOT
              value: /host/proc
            - name: SYSFS_ROOT
              value: /host/sys
            - name: VECTOR_LOG
              value: info
#          ports:
#            - containerPort: 9090
#              name: prom-exporter
#              protocol: TCP
          volumeMounts:
            - mountPath: /vector-data-dir
              name: data
            - mountPath: /etc/vector/
              name: config
              readOnly: true
            - mountPath: /var/log/
              name: var-log
              readOnly: true
            - mountPath: /var/lib
              name: var-lib
              readOnly: true
            - mountPath: /host/proc
              name: procfs
              readOnly: true
            - mountPath: /host/sys
              name: sysfs
              readOnly: true
      volumes:
        - name: config
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: vector
        - hostPath:
            path: /var/lib/vector
            type: ''
          name: data
        - hostPath:
            path: /var/log/
            type: ''
          name: var-log
        - hostPath:
            path: /var/lib/
            type: ''
          name: var-lib
        - hostPath:
            path: /proc
            type: ''
          name: procfs
        - hostPath:
            path: /sys
            type: ''
          name: sysfs
