apiVersion: v1
kind: Service
metadata:
  name: vector-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: vector
  ports:
    - name: datadog-agent
      port: 8282
      protocol: TCP
      targetPort: 8282
    - name: fluent
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: logstash
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: splunk-hec
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: statsd
      port: 8125
      protocol: TCP
      targetPort: 8125
    - name: syslog
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: vector
      port: 6000
      protocol: TCP
      targetPort: 6000
    - name: prom-exporter
      port: 9090
      protocol: TCP
      targetPort: 9090
