kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      enabled: true
      paths:
        - /var/log/containers/test-*.log

    # Send events to Logstash.
    output.logstash:
      enabled: true
      hosts: ["logstash:5044"]
      index: filebeat

    # You can set logging.level to debug to see the generated events by the running filebeat instance.
    logging.level: info
    logging.to_files: false
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644
