kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: filebeat-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io