kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash
data:
  logstash.yml: |
    path.config: /usr/share/logstash/pipeline

  logstash.conf: |
    input {
      beats {
        port => {{ .Values.service_port }}
      }
    }
    output {
      elasticsearch {
          hosts => [ "{{ .Values.elasticsearch_url }}" ]
          index => "logstash-%{[kubernetes][namespace]}-%{+YYYY.MM.dd}"
          ssl => false
      }
    }
