kind: Deployment
apiVersion: apps/v1
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi

        env:
          - name: ELASTICSEARCH_URL
            value: {{ .Values.elasticsearch_url }}
        ports:
        - containerPort: {{ .Values.service_port }}