kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-agent-standalone
  labels:
    k8s-app: elastic-agent-standalone
rules:
  - apiGroups:
      - coordination.k8s.io
    resources: ["leases"]
    verbs: ["get", "create", "update"]
