kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash-oss:7.7.1
        ports:
        - containerPort: {{ .Values.service_port }}
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
        env:
          - name: ELASTICSEARCH_URL
            value: {{ .Values.elasticsearch_url }}
        resources:
            requests:
              memory: "200Mi"
              cpu: "150m"
      volumes:
      - name: config-volume
        configMap:
          name: logstash
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash
          items:
            - key: logstash.conf
              path: logstash.conf
