kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: {{ .Values.service_port }}
    targetPort: {{ .Values.service_port }}
